import React, { useState } from "react";
import { SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { StatusBar } from "expo-status-bar";

const C = { blue:"#0A7CFF", navy:"#0B1F3A", bg:"#F6F8FC", text:"#0F172A", muted:"#64748B", line:"#E2E8F0", green:"#22C55E", white:"#FFFFFF" };

function Button({title,onPress,secondary=false}:{title:string;onPress:()=>void;secondary?:boolean}) {
  return <TouchableOpacity onPress={onPress} style={[s.btn, secondary && s.btn2]}><Text style={[s.btnText, secondary && {color:C.blue}]}>{title}</Text></TouchableOpacity>;
}
function Brand(){ return <View style={s.brand}><View style={s.mark}><Text style={s.markText}>⌗</Text></View><View><Text style={s.logo}>QR <Text style={{color:C.blue}}>Go</Text></Text><Text style={s.tag}>Escaneou. Avisou. Entregou.</Text></View></View>; }
function Card({children}:{children:React.ReactNode}){return <View style={s.card}>{children}</View>}

export default function App(){
 const [screen,setScreen]=useState<"welcome"|"login"|"home"|"qr"|"deliveries"|"chat"|"away"|"profile">("welcome");
 const [email,setEmail]=useState("");
 if(screen==="welcome") return <SafeAreaView style={s.root}><StatusBar style="dark"/><View style={s.center}><Brand/><Text style={s.hero}>Receba suas entregas com mais praticidade.</Text><Text style={s.p}>Um QR Code conecta o entregador diretamente com você sem revelar seu telefone.</Text></View><Button title="Entrar" onPress={()=>setScreen("login")}/><Button secondary title="Criar minha conta" onPress={()=>setScreen("login")}/></SafeAreaView>;
 if(screen==="login") return <SafeAreaView style={s.root}><Brand/><Text style={s.h1}>Entrar</Text><Text style={s.p}>Acesse sua conta QR Go.</Text><TextInput style={s.input} value={email} onChangeText={setEmail} placeholder="E-mail ou celular"/><TextInput style={s.input} secureTextEntry placeholder="Senha"/><Button title="Entrar" onPress={()=>setScreen("home")}/><Button secondary title="Esqueci minha senha" onPress={()=>{}}/></SafeAreaView>;
 if(screen==="home") return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={{gap:14}}><Brand/><Text style={s.h1}>Olá, Gabriela 👋</Text><Card><Text style={s.h2}>Residencial Jardim</Text><Text style={s.p}>Torre B — Apto 305</Text><Text style={s.ok}>● Disponível para receber</Text></Card><View style={s.grid}><Button title="Meu QR" onPress={()=>setScreen("qr")}/><Button title="Entregas" onPress={()=>setScreen("deliveries")}/><Button secondary title="Conversas" onPress={()=>setScreen("chat")}/><Button secondary title="Modo ausente" onPress={()=>setScreen("away")}/></View><Card><Text style={s.h2}>Última entrega</Text><Text style={s.body}>Mercado Livre</Text><Text style={s.p}>Hoje — 14:32</Text><Text style={s.ok}>✓ Entrega concluída</Text></Card><Button secondary title="Perfil" onPress={()=>setScreen("profile")}/></ScrollView></SafeAreaView>;
 if(screen==="qr") return <SafeAreaView style={s.root}><Brand/><Text style={s.h1}>Meu QR Code</Text><Card><Text style={s.h2}>Residencial Jardim</Text><Text style={s.p}>Torre B — Apto 305</Text><View style={s.qr}><Text style={{fontSize:70}}>▦</Text><Text style={s.p}>QR X8K29Q</Text></View><Text style={s.ok}>● Ativo</Text></Card><Button title="Salvar QR" onPress={()=>{}}/><Button secondary title="Compartilhar" onPress={()=>{}}/><Button secondary title="Gerar novo QR" onPress={()=>{}}/><Button secondary title="Voltar" onPress={()=>setScreen("home")}/></SafeAreaView>;
 if(screen==="deliveries") return <SafeAreaView style={s.root}><Brand/><Text style={s.h1}>Entregas</Text>{[["Mercado Livre","Hoje — 14:32","✓ Concluída"],["iFood","Hoje — 12:15","✓ Entregue pessoalmente"],["Shopee","Ontem — 18:20","✓ Portaria"],["Correios","23/09","Não concluída"]].map(x=><Card key={x[0]}><Text style={s.h2}>{x[0]}</Text><Text style={s.p}>{x[1]}</Text><Text style={x[2].startsWith("✓")?s.ok:s.err}>{x[2]}</Text></Card>)}<Button secondary title="Voltar" onPress={()=>setScreen("home")}/></SafeAreaView>;
 if(screen==="chat") return <SafeAreaView style={s.root}><Brand/><Text style={s.h1}>Entrega em andamento</Text><Card><Text style={s.body}>Entregador</Text><Text style={s.p}>Cheguei com sua entrega. Estou na portaria.</Text></Card><Card><Text style={s.body}>Você</Text><Text style={s.p}>Já estou descendo.</Text></Card><TextInput style={s.input} placeholder="Digite uma mensagem"/><Button title="Enviar" onPress={()=>{}}/><Button secondary title="Voltar" onPress={()=>setScreen("home")}/></SafeAreaView>;
 if(screen==="away") return <SafeAreaView style={s.root}><Brand/><Text style={s.h1}>Modo ausente</Text><Card><Text style={s.h2}>Estou ausente</Text><Text style={s.p}>Defina o que o entregador deve fazer quando você não estiver disponível.</Text></Card><TextInput style={[s.input,{height:100}]} multiline value="Pode deixar a encomenda na caixa ao lado do portão."/><Button title="Salvar" onPress={()=>setScreen("home")}/></SafeAreaView>;
 return <SafeAreaView style={s.root}><Brand/><Text style={s.h1}>Perfil</Text><Card><Text style={s.h2}>Gabriela</Text><Text style={s.p}>Conta do morador</Text></Card>{["Minhas residências","Minha assinatura","Preferências de entrega","Notificações","Segurança e privacidade"].map(x=><Button key={x} secondary title={x} onPress={()=>{}}/>)}<Button secondary title="Voltar" onPress={()=>setScreen("home")}/></SafeAreaView>;
}

const s=StyleSheet.create({
 root:{flex:1,backgroundColor:C.bg,padding:20,gap:12},center:{flex:1,justifyContent:"center",gap:18},
 brand:{flexDirection:"row",alignItems:"center",gap:10,marginBottom:10},mark:{width:48,height:48,borderRadius:14,backgroundColor:C.blue,alignItems:"center",justifyContent:"center"},markText:{fontSize:28,color:"#fff",fontWeight:"900"},logo:{fontSize:26,fontWeight:"900",color:C.navy},tag:{fontSize:10,color:C.muted},
 hero:{fontSize:30,lineHeight:36,fontWeight:"900",color:C.text},h1:{fontSize:28,fontWeight:"900",color:C.text},h2:{fontSize:18,fontWeight:"800",color:C.text},body:{fontSize:15,fontWeight:"700",color:C.text},p:{fontSize:15,lineHeight:22,color:C.muted},ok:{color:C.green,fontWeight:"800"},err:{color:"#EF4444",fontWeight:"800"},
 card:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:18,padding:16,gap:6},btn:{minHeight:52,borderRadius:14,backgroundColor:C.blue,alignItems:"center",justifyContent:"center",paddingHorizontal:16},btn2:{backgroundColor:C.white,borderWidth:1,borderColor:C.blue},btnText:{color:"#fff",fontSize:16,fontWeight:"800"},input:{height:52,borderRadius:14,borderWidth:1,borderColor:C.line,backgroundColor:"#fff",paddingHorizontal:14,color:C.text},grid:{gap:10},qr:{alignItems:"center",justifyContent:"center",padding:28,marginVertical:10,backgroundColor:"#fff",borderWidth:1,borderColor:C.line,borderRadius:16}
});